name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=0.47.0 sh
          # Add pixi to PATH
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Run tests
        run: pixi run test

      - name: Run formatter
        run: pixi run format
